const targetUrl = process.env.TARGET_URL ?? 'http://127.0.0.1:8080';
const durationSeconds = Number.parseInt(process.env.DURATION_SECONDS ?? '30', 10);
const concurrency = Number.parseInt(process.env.CONCURRENCY ?? '25', 10);
const writeRatio = Number.parseFloat(process.env.WRITE_RATIO ?? '0.05');
const adminToken = process.env.ADMIN_TOKEN ?? '';

const deadline = Date.now() + durationSeconds * 1000;
const latencies = [];
let failed = 0;
let requests = 0;

function percentile(values, p) {
  if (values.length === 0) {
    return 0;
  }
  const sorted = [...values].sort((a, b) => a - b);
  const index = Math.min(sorted.length - 1, Math.ceil((p / 100) * sorted.length) - 1);
  return sorted[index];
}

async function request(path, options = {}) {
  const start = performance.now();
  const response = await fetch(`${targetUrl}${path}`, {
    headers: {
      Accept: 'application/json',
      ...(options.body ? { 'Content-Type': 'application/json' } : {}),
      ...(adminToken ? { Authorization: `Bearer ${adminToken}` } : {})
    },
    ...options
  });
  await response.arrayBuffer();
  latencies.push(performance.now() - start);
  requests += 1;
  if (!response.ok) {
    failed += 1;
  }
}

async function worker(id) {
  while (Date.now() < deadline) {
    if (Math.random() < writeRatio) {
      await request('/api/incidents', {
        body: JSON.stringify({
          description: `Generated by load worker ${id}`,
          owner: 'load-test',
          priority: 'low',
          title: `Load sample ${Date.now()}`
        }),
        method: 'POST'
      });
    } else {
      await request('/api/incidents');
    }
  }
}

await Promise.all(Array.from({ length: concurrency }, (_, index) => worker(index + 1)));

const seconds = durationSeconds;
console.log(JSON.stringify({
  concurrency,
  durationSeconds,
  failed,
  p50Ms: Number(percentile(latencies, 50).toFixed(2)),
  p95Ms: Number(percentile(latencies, 95).toFixed(2)),
  requests,
  requestsPerSecond: Number((requests / seconds).toFixed(2)),
  targetUrl,
  writeRatio
}, null, 2));
